### PR TITLE
Symbol docs (Work in Progress)

### PR DESCRIPTION
**Pull request by rkoeninger**
Added `write-doc`, `read-doc`, `info` and `function?` functions for interactive inspection of the function namespace.

`function?` allows user to determine if a function is defined. `info` prints information about a function.

Example:

```
(0+) (define inc {number --> number} X -> (+ 1 X))

(1+) (write-doc inc "Increments a number.")

(2+) (info inc)
[number --> number]

Increments a number.
```

The rest of the `write-doc` calls in `types.shen` still need to be filled out.

Should there be a separate function for docs on symbols in the symbol namespace?

Standard function docs could be generated from this with Shen code that takes the typesigs/docstrings and emits them as HTML/Markdown.

Thoughts?

### CODE REVIEW

**Comment by deech** [comment]
I appreciate the work that went into this but I'm leary about adding this to the official sources. I'm much more in favor of a doc format that's completely separate from the language itself (like Haddock) with tooling to retrieve at the REPL rather than building it into the language. For example, I don't really want these doc strings bloating up a binary executable. Why not make it a library so users can choose?

**Comment by tizoc** [comment]
I guess this is the enhancement you mentioned in the other issue, so you will probably agree here: I think it would be better implemented in a separate file. That way ports can easily ignore it if they don't want the docs by default, and have the option to load the file at runtime when needed.

Also, I agree with @deech (who posted as I was writing this, saving me some typing :) )

**Comment by rkoeninger** [comment]
There could be `*include-docstrings*` or `*exclude-docstrings*`, which a port could set, and have the calls to `write-doc` wrapped under a conditional:

```lisp
(if (value *include-docstrings*)
  (write-doc nth "Returns the element at the 1-based index in a list.")
  ...etc...)
```

As for having the docstrings in the language source, that seems to be the norm. Some do it as comments instead, but then we would need an additional parser that retains comments so we know what they're attached to.

There isn't a standard way to do libraries in Shen, is there? If network streams were available, then we could host libraries in GitHub repo and have a function for fetching and loading a library if not already present.

```lisp
(0-) (install docs)
loaded

(1-) (install docs) \\ already loaded at this point
skip

(2-) (info nth)
[number --> [[list A] --> A]]

Gets the elements at the 1-based index in a list.

Source not available.

(3-) (install-github math "rkoeninger/my-shen-libs")
loaded

(4-) (sqrt 25)
5
```

Afraid to think about versioning, though.

**Comment by tizoc** [comment]
Do those flags offer any advantage over a separate file? (not talking about an external library here, just a separate file, networking is a non-issue in that case).

Regarding the other stuff, there isn't yet a standard way to do libraries, and of course no portable networking either (or a portable way of doing more advanced IO and calling external processes). That of course, is a huge blocker for having a nice-to-use libraries collection and packaging system.

All those things are easy to solve on a per-port basis, because most of the underlying platforms would provide what you need, and most ports provide an easy way to access such functionality. What is a much harder problem is solving such things in a portable way, that works well across all ports.

I have to complete the Shen rewrite of the kl->scheme compiler and support for Chez, once that is done I'm going to try to solve the I/O issues for that port specifically at first, then start discussions to see how other ports could implement such APIs, or how the APIs would have to be changed so that enough is implementable across (the active?) ports. If other port maintainers can do the same, then thats even better, because more reference implementations will make things easier.

Btw, in case you didn't know about it already, you may be interested in this repository: https://github.com/vasil-sd/shen-libs

Some things that may interest you:

- This file where a macro for docstrings is simplemented: https://github.com/vasil-sd/shen-libs/blob/master/macros/macros.shen
- A module system https://github.com/vasil-sd/shen-libs/blob/master/modulesys.shen and https://github.com/vasil-sd/shen-libs/blob/master/modulesys_howto.md
- Another (not exactly, but packages): https://github.com/vasil-sd/shen-libs/blob/master/packages/packages.shen

**Comment by rkoeninger** [comment]
Linking for reference: https://github.com/hraberg/shen.clj/blob/master/src/shen/overwrite.clj#L46

**Comment by rkoeninger** [comment]
@tizoc The flags are to allow the optional inclusion of code/data in one big .kl file as discussed in #39.

I think I've seen [shen-libs](https://github.com/vasil-sd/shen-libs) before, but had forgotten about it. There's some good stuff in there, but it doesn't help if people don't know it exists. Thus my musing about an `(install package)` functionality that could pull these in with a short, simple command.

A Shen executable can already be easily acquired with `gem install shen-ruby` or `nuget install ShenSharp`. Getting common libraries needs to be just as easy if Shen is going to gain a user base.

**Comment by tizoc** [comment]
> @tizoc The flags are to allow the optional inclusion of code/data in one big .kl file as discussed in #39.

Sounds good to me. Does this work for you @deech ? Also, I suppose #41 could be used for stuff like this.

> There's some good stuff in there, but it doesn't help if people don't know it exists.

Yeah, I just pointed at it because there was some code for handling docs there that you may want to get ideas from. In particular, I like the idea of supporting docstrings (not necessary for the kernel, but maybe cool to have when writing libraries).

> Getting common libraries needs to be just as easy if Shen is going to gain a user base.

Agree. I plan to add networking support to shen-scheme once I have it working with Chez, and I see you already started with that in ShenSharp, in the future we can revise our APIs and try to normalize them (ideally with the input of other port writers too). With basic networking, filesystem operations and a little more advanced I/O APIs that are portable across ports we will be able to write a package handling tool that can be used by every port (doesn't have to be anything complicated, being able to fetch stuff from Github like you mentioned is more than enough, at least at first).

**Comment by rkoeninger** [comment]
I added a `shen-sharp.download` function real quick that is basically `curl`. With the addition of:

```clojure
(0-) (define import Url -> (map (function eval) (read-from-string (shen-sharp.download Url))))
```

I can import the code from [a simple fibonacci file in a Gist](https://gist.github.com/rkoeninger/e4866644074552957f6e4df5919d3a28):

```clojure
(1-) (import "https://gist.github.com/rkoeninger/e4866644074552957f6e4df5919d3a28/raw/0cde4b0fe325ca478fde3ed701f512d787ee1a10/fibonacci.shen")
[fibonacci-h fibonacci]

(2-) (map (function fibonacci) [0 1 2 3 4 5 6 7 8])
[0 1 1 2 3 5 8 13 21]
```

You'd have to have some sort of aliasing for prefixing the url to make it more useble, but it's close in functionality.

**Comment by bsima** [comment]
> Afraid to think about versioning, though.

@rkoeninger: In @deech's ["Shen trick shots" talk](https://youtu.be/BUJNyHAeAc8?t=1470), he prototypes a way to extract inferred types ([source code](https://github.com/deech/lambdaconf-shen-talk/blob/master/signature.shen)) which can then be used to enforce semantic versioning the same way [Elm](http://elm-lang.org/) does. I think something like this would be the correct strategy.

**Comment by rkoeninger** [comment]
I guess it's a no for this PR. I'll close it and keep the branch around on my fork for future reference.

**Pull request closed without merging**
