### PR TITLE
Add library to normalize command-line handling of shen launchers

### LINKED ISSUE #79: Optional normalized command-line arguments handling
As suggested by @vrescobar, ports could normalize the command line flags they accept and how they behave.

I don't think making it a part of the kernel is a good idea, but an alternative is to include an optional library that ports can use to handle the common flags.

I have an unfinished version based on what Shen/CL and Shen/Scheme do, will submit it for review soon.

### PR DESCRIPTION
**Pull request by tizoc**
Fixes #79

Still not complete, needs to support extension by the ports and the help messages are missing.

The idea is that some flags are only accepted as first flags, because it doesn't make sense to mix them with others (I added "--repl" there but maybe that one should be allowed as a "last flag" too).

Unlike in Shen/CL, all flags that are not on the list of "first flags" are validated before anything is executed.

### CODE REVIEW

**Comment by tizoc** [comment]
Ports that use this would have to obtain a list of [ExeName | Arguments] and pass it to `(launch-shen.launch-shen [ExeName | Arguments])`.

I'm not sure yet about how to handle extensions (needs to take into account help printing too).

**Comment by tizoc** [comment]
Oh, short version of flags is something else that is missing here, but very easy to solve.

**Comment by tizoc** [comment]
There is an update pending for this. I'm making the launcher function return different values depending on what the port is expected to do (nothing with exit code 0, process unknown arguments, error out and exit with an error code if supported, etc)

**Comment by tizoc** [comment]
@rkoeninger this was made mainly with Shen/CL and Shen/Scheme in mind. Does it all look ok for ShenScript and ShenSharp to you? anything you would change?

**Comment by rkoeninger** [comment]
This should work for ShenScript and ShenSharp. And I like keeping it in the same repo instead of having to pull in another one.

For the "first flags" thing - The behavior in shen-cl was the result of playing with it for a while and wanting to realize a handful of scenarios:
  * start repl: `shen`
  * load scripts, eval expressions (and set symbols) and exit: `shen -l make.shen -e "(make)"`
  * load scripts, eval expressions (and set symbols) and start repl: `shen -l prelude.shen -e "(setup)" -r`

Does this do all of these?

Technically, you could do `-l`, `-s`, `-r` with `-e`, but they seemed like good common shortcuts. Any other shortcuts we would want to add?

I added the `--set` option to shen-cl after thinking about what the `*argv*` would be used for. Would you scan it for values that you would then assign to globals? What else is it for? And you'd have to filter out options that are directed at the Shen impl vs at the host platform that Shen is running on vs args to your program.

Is `ExeName` needed?

**Comment by tizoc** [comment]
@rkoeninger "first flag" is just "commands" now (similar to git, opam, etc). Ignore all my comments on this PR (most are outdated) and look at the help string and docs at the end of the file.

It does everything you mention except being able to start the REPL after the eval/loads commands, but it is very easy to fix. We have two choices here, either have the `repl` command accept the same arguments as the `eval` command, or add a `-r/--repl` flag to `eval` that launches the REPL after being done with everything else, not sure which option I like more.

> And you'd have to filter out options that are directed at the Shen impl vs at the host platform that Shen is running on vs args to your program.

That is done by the `script` command, which behaves like Shen/Scheme's `--script`. The first parameter after the script is the script to run, the rest are arguments to the script. Before the script is executed `*argv*`is set to the list of everything that comes after the `--script` flag (`script` command in the case of how it was implemented here). Note that `*argv*` is not touched unless `script` is being used, I don't think it makes sense for it to have a value when running in other modes.

`ExeName` is needed to correctly build the help message, and it is also useful in cases when one wants to behave differently depending on the name of the program being called. It is also what one expects from ARGV (an array with ARGV[0] = executable). I would guess any port that can access the command line arguments can also access the executable name, and if it can't then it can fake it.

**Comment by tizoc** [comment]
This one also solves #4 btw, at least at a basic level.

**Comment by rkoeninger** [comment]
Ok, I get the first flag thing now, and that must be why some of the options in the `launch-shen` function don't have hyphens, it's `shen script ...` not `shen --script ...`.

If the first option you want to specify is an `--eval` you have to write it `eval`? `--eval` won't work?

**Comment by rkoeninger** [comment]
Also, is the motivation for `*args*` for the use case where a script is being called by a bash script or something similar? So one could write `shen script whatever.shen arg1 arg2 arg3`?

**Comment by tizoc** [comment]
Re: `--eval`

Yes, the only flags at the root are `--version` and `--help` (and their short versions), because those are very standard. Everything else is subcommands. Ports are free to add more commands and flags (even at the root) as they see fit, what is provided here is a list of subcommands and flags that should work as-is in any port that is able to run the Shen REPL in it's current form.

Re: `*argv*`

That is correct. Example with Shen/Scheme (it uses `--script` instead):

```
#!/usr/bin/env shen-scheme --script

(output "~R~%" (value *argv*))
```

```
$ ./script.shen
("./script.shen")
$ ./script.shen a b c d
("./script.shen" "a" "b" "c" "d")
```

Same with `shen-scheme --script program.shen program arguments here`.

**Comment by tizoc** [comment]
Btw, I want to clarify something, these are not "libraries" in the traditional sense, thats why I changed the directory name here and in the `feature-expand` PR to "extensions".

These are extra files that ports can include to get the extra functionality. The porting instructions document will have to be extended with this information (o a new document added for explaining the extensions).

**Comment by rkoeninger** [comment]
I was wondering about the hash-bang line. Does there need to be a kernel change to support that? Or is the launcher going to strip it out before parsing and evaluating the file?

**Comment by tizoc** [comment]
@rkoeninger it depends on how the line looks, as long as there are no parentheses in there it is going to be parsed as a bunch of symbols by Shen and ignored, nothing is done by Shen/Scheme to handle hashbangs.

**Comment by rkoeninger** [comment]
Also, the `quiet-load` function is questionable as `eval-without-macros` won't do typechecking I think? Looking at the file `load.shen`, it does a lot more when a file is loaded with typechecking on. Could `shen.load-help` be used instead?

**Comment by tizoc** [comment]
No, because if you want typechecking you still have to do more. The typechecking flag has to be enabled before the file is loaded, and types have to be defined before the file is loaded too. The `script` command isn't mean to be THE way of running programs, it is just a convenience utility for a common use case.

It is possible to have scripts work with typechecking, it is just not a simple thing to do right now (using `shen.load-help` is not enough) with the current evaluation model Shen employs, solving that is a bigger than that what this PR is solving. Something else that is not solved here is calling `load` from inside scripts. It works, but it is not "silent".

**Comment by rkoeninger** [comment]
Could set typechecking with the `--set` flag like below.

```shen
λ shen -s shen.*tc* true -l typed-code.shen -r

filter : ((A --> boolean) --> ((list A) --> (list A)))
run time: 0.0 secs

typechecked in 354 inferences

Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 21.1
running under Common Lisp, implementation: SBCL
port 2.5 ported by Mark Tarver
exit REPL with (cl.exit)

(0+) filter
filter : ((A --> boolean) --> ((list A) --> (list A)))
```

Should there be a `-t` option that takes +/- or on/off or true/false? Would that work with the hash-bang like `#!/usr/bin/env shen -t + --script`?

**Comment by vrescobar** [comment]
I tested it and at the moment is not behaving so much as I would expect:
```bash
$ cat test.shen 
#!/Users/vresko/projects/shen-sources/shen-cl/shen -l
(print "hello")

$ ./test.shen 
#!/Users/vresko/projects/shen-sources/shen-cl/shen
-l
"hello""hello"

run time: 0.0010000001639127731 secs

$ shen-cl/shen test.shen 

unrecognized option: test.shen

$ shen-cl/shen -l test.shen 
#!/Users/vresko/projects/shen-sources/shen-cl/shen
-l
"hello""hello"

run time: 0.0010000001639127731 secs
```

The shebang is giving problems as I cannot have a script and still call it with the interpreter, I think some non-elegant way to detect the first line of the script should be implemented so it is skip. The double echoing and the printed run time values are beyond my understanding and I wanted to ask that in the email list actually.

The error when trying to execute `shen script.shen`: instead of say that it is an unrecognized option we could just run the file (last option in the list). Typically interpreters do not need any flag to load a script, so I feel quite weird to see the option `shen -l file.shen` or `shen --script file.shen`. Couldn't just be:

```
$ shen --help

Usage: shen [options] [script]

If no script is given shen will launch the REPL.

COMMAND LINE OPTIONS
       -t  
              Enforce the type checker
       -e command
              Specify the command to execute.  This terminates the option list (following options are passed  as  arguments to the command).
       -h ,  -? ,  --help
              Prints the usage for the interpreter executable and exits.
       -v, --version 
              Prints the Shen version number of the executable and exits.
```


This way we can just have regular shell scripts like any other interpreter:


```clj
#!/usr/bin/shen
(print "hello scripts")
```

And I would expect to run and behave the interpreter like that:

```
$ shen example.shen
hello scripts
$ ./example.shen
hello scripts
```

**Comment by rkoeninger** [comment]
@vrescobar The double printing is because the `print` is having the effect of printing the string and then the value the `(print "hello")` evaluates to then gets printed as part of the `load` process. (`(print "hello")` evaluates to `"hello"`) `load` prints the result of evaluating each top-level form in the file.

**Comment by vrescobar** [comment]
> @vrescobar The double printing is because the `print` is having the effect of printing the string and then the value the `(print "hello")` evaluates to then gets printed as part of the `load` process. (`(print "hello")` evaluates to `"hello"`) `load` prints the result of evaluating each top-level form in the file.

I would expect this effect to happen only in the REPL. I am looking at the code when I have some time, I think there is a global variable that silents the output, not sure if it is to exactly deactivate this behave (the current `--quiet` option appears to be broken)

**Comment by rkoeninger** [comment]
`--quiet` isn't really broken, just bad. It disables output from `print` and the `output` macro, meaning most output.

**Comment by tizoc** [comment]
Just tested this with Shen/Scheme, seems to work fine. [Diff here](https://github.com/tizoc/shen-scheme/commit/f51d730bf27260d7631edd7e34d1be1eee55444d).

I will be merging this soon.

@vrescobar `shen script.shen` is quite script-oriented, not all ports are focused on doing that (Shen/Scheme mainly runs scripts now but my plan is to do compilation by default). Any port that wants to support that format by default can do so, I just don't think this extension is the right place for that. The intention is to just support a few common operations that any Shen port able to start the REPL will be able to support as-is, not to handle every possible option.

**Comment by rkoeninger** [comment]
Whole-heartedly agree with renaming `shen.shen` to `shen.repl` as referenced in #87 

I really think the REPL should be an extension and not the kernel, but that's another conversation.

**Comment by tizoc** [comment]
Merging as-is for now, may look into adding support for setting the tc flag in the future.

**Comment by vrescobar** [comment]
sorry for the last weeks job and personal life kept me away from shen. Since sources cannot bootstrap a whole interpreter by themselves, I want to take a look at it in combination of shen-cl port.

**Pull request merged**
