### PR TITLE
Whitespace cleanup

### PR DESCRIPTION
**Pull request by tizoc**
Nothing interesting, just switched to Unix newlines and removed trailing whitespace.

### CODE REVIEW

**Comment by tizoc** [comment]
Done in OSX with `dos2unix` and `sed -i '' -e's/[[:space:]]*$//'` btw.

**Comment by tizoc** [comment]
@deech @gravicappa @mthom are you all ok with me merging this? (it is just for cleaner diffs in the future if we start introducing changes)

**Comment by deech** [comment]
Go for it! Looks great.

**Comment by gravicappa** [comment]
Sure!

**Comment by tizoc** [comment]
Ok, cool. Will probably cleanup a bit more (reformatting for consistency) before merging.

**Comment by tizoc** [comment]
I'm thinking I should do this on top of 19.2 instead, then reapply the patches we have on top of it, otherwise if a new release is created the diff is going to be useless.

**Pull request closed without merging**
