### PR TITLE
Add feature library for conditional code expansion

### LINKED ISSUE #41: Feature based conditional expansion
Macro for feature based expansion, will be useful mainly for portable libraries that need different code evaluated/compiled depending on which platform is loading it.

May be useful in the kernel too to handle optional features.

Based on Scheme's [SRFI-0](https://srfi.schemers.org/srfi-0/srfi-0.html)

```lisp
\* ports would define their own list, with one of the elements being the port name *\
(set *features* [shen-elisp feat1 feat2])

(defmacro cond-expand-macro
  [cond-expand] -> (error "Unfulfilled cond-expand.")
  [cond-expand true Body]
    -> Body
  [cond-expand [and] Body | MoreClauses]
    -> Body
  [cond-expand [and Feature | MoreFeatures] Body | MoreClauses]
    -> [cond-expand
        Feature [cond-expand [and | MoreFeatures] Body
                             | MoreClauses]
        | MoreClauses]
  [cond-expand [or] Body | MoreClauses]
    -> [cond-expand | MoreClauses]
  [cond-expand [or Feature | MoreFeatures] Body | MoreClauses]
    -> [cond-expand
        Feature Body
        true [cond-expand [or | MoreFeatures] Body | MoreClauses]]
  [cond-expand [not Feature] Body | MoreClauses]
    -> [cond-expand
        Feature [cond-expand | MoreClauses]
        true Body]
  [cond-expand Feature Body | MoreClauses]
    -> Body where (element? Feature (value *features*))
  [cond-expand Feature Body | MoreClauses]
    -> [cond-expand | MoreClauses])
```

used like this:

```lisp
(cond-expand
 feat1 (pr "has feat1c#10;") \\ prints this
 feat2 (pr "has feat2c#10;"))

(cond-expand
 no-feat (pr "has no-featc#10;")
 true (pr "doesn't have no-featc#10;")) \\ prints this

(cond-expand
 (and feat1 feat2) (pr "has feat1 and feat2c#10;") \\ prints this
 true (pr "doesn't have both feat1 and feat2c#10;"))

(cond-expand
 (or no-feat feat1 feat2) (pr "has no-feat or feat1 or feat2c#10;") \\ prints this
 true skip)

(cond-expand
 (not no-feat) (pr "doesn't have no-featc#10;") \\ prints this
 no-feat (pr "has no-featc#10;")
 true skip)

(cond-expand
 no-feat (pr "has no-featc#10;")) \\ raises error
```

It is just a first draft, it is incomplete but wanted to share to get other's thoughts on this.

### PR DESCRIPTION
**Pull request by tizoc**
Fixes #41

### CODE REVIEW

**Comment by rkoeninger** [comment]
Could the feature symbols for platform just be `cl`, `scheme`, `js` and implementation `sbcl`, `chez`, `node`. Or the implementations could be scoped like `cl.sbcl`, `js.web.chromium`.

In order to match these you could have `feature-expand` match on prefixes or just have the port supply a little of increasingly precise symbols like `[js js.web js.web.chromium js.web.chromium.brave]`

**Comment by tizoc** [comment]
Adding prefix matching handling like more complication than it is worth for what is gained, neither Common Lisp or Scheme seem to have a problem with not having that (neither do the preprocessors I'm familiar with). But using `.` to keep the hierarchy of features sounds good, will update the document.

Note that `shen/scheme`, `shen/js`, `shen/cl`, etc are the names of the ports, and quite unambiguous, thats why I like those more than just `scheme`, `js` and `cl`.

**Comment by rkoeninger** [comment]
I was thinking `cl` instead of `shen-cl` because I wanted to refer to the platform specifically and not the port. `cl` would mean `cl.` functions (yeah, they're `lisp.` instead) would be available and `shen-cl` would mean `shen-cl.` functions would be available. There should be a one-to-one correspondence between platforms and ports anyway, but then again, I made ShenScript when shen-js already existed so 🤷‍♂

**Comment by tizoc** [comment]
Just updated `make.shen` so that it compiles extensions to klambda too (including the copyright at the top of whatever file is being compiled).

I think this is ready to be merged, documentation and convention details can be updated later.

**Pull request merged**
