### PR TITLE
Initial work on benchmarks

### PR DESCRIPTION
**Pull request by tizoc**
# List
### Constructors
- [x] absvectors
- [x] vectors
- [x] strings
- [x] tuples
- [x] dicts
### Accessors (read and write)
- [x] tuple
- [x] string
- [x] absvector
- [x] vector
- [x] dict
## Equality checks
- [x] number
- [x] symbol
- [x] string
- [x] list
- [x] absvector
### Basic
- [x] Lambda calls
- [x] Thaw
- [x] trap-error without raising
- [x] trap-error raising
### trap-error for obtaining defaults
- [x] get
- [x] value
- [x] <-address
- [x] <-vector
- [x] shen.<-dict
### Pattern matching
- [x] big case with lists
- [x] big case with strings
- [x] big case with vectors
- [x] big case with tuples
### Basic operations on stdio
- ~write-byte~
- ~read-byte~
### Basic operations on file
- ~write-byte~
- ~read-byte~
- ~bulk reads~
## Compiler helper functions (that help the compiler be faster)
- [x] shen.pvar?
- [x] variable?
- [x] symbol?
- [x] shen.sysfunc?

**TODO** add more

### CODE REVIEW

**Comment by rkoeninger** [comment]
Instead of just measuring the total time to run 10000 instances, could we gather each data point and measure total, mean, median, stddev?

Could run into timer resolution issues though - `get-time` doesn't have enough resolution and everything is `0`.

**Comment by rkoeninger** [comment]
Also, I've never been a fan of the Shen idiom of each function having to do recursion itself. Instead of

```shen
(define absvector-create-small
  V 0 -> V
  V N -> (absvector-create-small (absvector 1) (- N 1)))
```

can we do

```shen
(define repeat
  0 _ -> []
  N F -> (do (F) (repeat (- N 1) F)))

(repeat N (freeze (absvector 1)))
```

**Comment by tizoc** [comment]
That `repeat` function adds overhead because `F` is a dynamic application.

Self-recursion is the purest loop that Shen can represent.

Regarding `get-time`, thats true, but if you get 0 for so many runs, that means your port is fast enough for this test.

Another issue is that there is no portable way to call the garbage collector between tests, and that affects times.

Anyway, I don't want to get lost into that stuff now, the first thing is to get a decent amount of tests, once that is done the rest can be improved.

**Comment by tizoc** [comment]
> Self-recursion is the purest loop that Shen can represent.

Btw I know this is not performant on all platforms, thats why the control loop is there, that time should be subtracted from each result.

**Comment by tizoc** [comment]
> Instead of just measuring the total time to run 10000 instances, could we gather each data point and measure total, mean, median, stddev?

Tell me more about this because I'm not sure I understand. Example?

**Comment by rkoeninger** [comment]
Let's say I run a `(absvector 1)` x1000 benchmark and it says `5 sec`. So I infer it takes 5ms to allocate an array by computing only the mean. But it might be the case that it took 1-2ms just to allocate the first array and the rest are like 1us a piece. Maybe for some reason something gets lazily initialized or code is cold on the first few runs. Having a stddev and/or a mean that excludes outliers gives us a lot more insight as to what is going on than a flat number like total time or simple mean.

**Comment by tizoc** [comment]
That is kind of complicated to do at the Shen level, the problem is similar to how `get-time`'s resolution is. It is not something that I think can be solved portable, that would be up for each port to do.

Now, warmups can be done portably, all that should be required is to do a few runs before the real ones that are timed.

**Comment by tizoc** [comment]
Another thing that cannot be solved portably, but that most platforms can do, is knowing how much memory was allocating while running some piece of code.

**Comment by rkoeninger** [comment]
> knowing how much memory was allocating

Yeah, ideally we'd have both time and space measurements.

> do a few runs before the real ones that are timed

That doesn't address the issue of amortized (spread-out) spikes in time (or memory use). But if you're goal with this PR is to get the first draft in, then it's not a big deal. My suggestions come from what I've read and done with more "industrial-strength" testing.

**Comment by rkoeninger** [comment]
How are results going to be reported? Will the script just print them to the screen or make the results available in a global variable or something. That `(reset)` change I made to the test suite was so I could extract the failure count in [ShenScript's kernel test run](https://github.com/rkoeninger/ShenScript/blob/master/test/kernel/test.kernel.js#L60).

**Comment by tizoc** [comment]
For now, just printed, but eventually it should output structured data, it is useful for building tables and compare across versions of a port (like in https://github.com/Shen-Language/shen-cl/pull/46)

> But if you're goal with this PR is to get the first draft in, then it's not a big deal.

For this PR and in general. I don't know how it can be solved portably. The best I can think of is to make sure the components are separate enough so that ports can provide their own more sophisticated  runner instead of the one provided here, and maybe a document with suggestions/good-practices on how to measure the provided functions.

**Comment by tizoc** [comment]
As with everything, this could be improved more, but I think it is good enough for now. If nothing else comes up will be merging this PR soon.

**Pull request merged**
