### PR TITLE
Whitespace cleanup

### PR DESCRIPTION
**Pull request by tizoc**
Reviewed and working.

### CODE REVIEW

**Comment by tizoc** [comment]
Ok, just did a second pass on this. I still have to recompile to KLambda and make sure I didn't break anything (very unlikely, because no code was changed, if something changed it was by accident).

The reformatting changes can be seen in the "Reformatting" commit.

**Comment by tizoc** [comment]
Ok, there was an issue in `make.shen`, I already fixed it and make sure that everything is rebuilt correctly and that all tests pass.

**Comment by rkoeninger** [comment]
What do you think about removing commented-out code while you're in cleanup mode?

in declarations.shen:

```
\\(set *reader-macros* [])
```

in make.shen:

```
\\(systemf sum)
\\(systemf *stoutput*)
\\(systemf package?)
```

in t-star.shen:

```
\\(defprolog patthyps
 \\ (mode [] -) _ Hyp Hyp <--;
 \\ (mode [Pattern | Patterns] -) (mode [A --> B] -) [[Pattern : A] | PattHyp] Hyp 
   \\ <-- (patthyps Patterns B PattHyp Hyp);) 
```
```
\\(defprolog result-type
  \\(mode [] -) B B <--;
   \\(mode [_ | Patterns] -) (mode [A --> B] -) C <-- (result-type Patterns B C);) 
```

in tests/interpreter.shen:

```
   \*[cases X1 | Xn] -> (let Case1 (normal_form X1)
                           (if (= Case1 "no match")
                               [cases | Xn]
                               Case1))
   [cases] -> "error!"            
   [where X Y] -> [if X Y "no match"]
   [y-combinator [/. X Y]] -> (replace X [y-combinator [/. X Y]] Y)
   [X Y] -> (let X* (normal_form X)
               (let Y* (normal_form Y)
                  (if (or (eval_error? X*) (eval_error? Y*))
                      "error!"
                      [X* Y*])))*\
```

in tests/tests.shen:

```
\* (report "FPQi chapter 2"
   (load "fruit machine.shen") loaded
   (do (print (fruit-machine start)) ok) ok) *\
```
```
  \* (load "newton version 1.shen") loaded
   (newtons-method 4) 2
   (load "newton version 2.shen") loaded 
   (newtons-method 4) 2 *\
```
```
\* (report "red/black trees"
   (tc +) true
   (load "red-black.shen") loaded) *\
```

**Comment by tizoc** [comment]
@rkoeninger good catch, I didn't even go through the files in `tests/`.

**Comment by tizoc** [comment]
Ok, removed commented out code from shen source files and reformatted the test files. I'm not removing the commented out stuff in tests because I don't know yet why it is there (maybe those where tests for Qi that were not fully ported to Shen, not sure), may be useful.

**Pull request merged**
