### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by rkoeninger**
Added a Makefile that automates:
- Acquiring shen executable to generate klambda.
- Rendering of klambda.
- Packaging klambda and tests into release package.

### CODE REVIEW

**Comment by tizoc** [comment]
Hi @rkoeninger, sorry for the delay. I gave this a look the other day and it looks good, I just wasn't able to test it yet, which I will be doing soon.

**Comment by tizoc** [comment]
Ok, `make fetch` fails on OSX, because there is no prebuilt binary for OSX for shen-cl, but I can help with that. I have to go now, but I will take a look later.

**Comment by tizoc** [comment]
@rkoeninger there are some things that are now missing from the release tarball/zip like the README, changelog, certification pdf, docs, specification, etc. I think those should be part of the distribution.

**Comment by rkoeninger** [comment]
@tizoc My thought has been that the release archives are mainly for ports/porters and are probably going to be downloaded automatically like in `shen-cl`.

I was trying to keep it minimal and limit what's in the release archive to what a port is likely to need: `klambda/`, `tests/` and `LICENSE.txt`. `sources/` are in there too, but even those could be left out.

`shen-cl` does something similar where the archive only includes `shen[.exe]` and `LICENSE.txt`.

It's easy to add additional stuff to the release in the future, but it's hard to change or remove something that people downstream have already become dependent on.

Do you think anything post-`make` should be left out, (`shen-cl/` of course) or should it be everything in the repo + `klambda/`?

**Comment by tizoc** [comment]
@rkoeninger sorry, I forgot about this PR and totally dropped the ball on this.

I would include everything (at least, as long as it doesn't get as bloated as the original Shen releases, which included everything and were multiple megabytes in size). I expect such tarballs to be self-contained release packages, going to the git repository to obtain other stuff shouldn't be necessary.

**Comment by rkoeninger** [comment]
@tizoc FYI: since merging, i consolidated the docs on the master branch and added the docs, assets, changelog, readme to the release packages

**Pull request merged**
