### PR TITLE
Expand dynamic

### PR DESCRIPTION
**Pull request by tizoc**
Implementation of #83 

I still have to move all non-defun expressions inside a single (or many?) defun.

### CODE REVIEW

**Comment by tizoc** [comment]
@rkoeninger

**Comment by tizoc** [comment]
Shen/Scheme startup went down from 0.35 to 0.23 when using the new generated files.

**Comment by tizoc** [comment]
The reason I mention the possibility of separating the generated code into separate defuns is that some of it is required for when the program calls the compiler (typechecking code, required by the REPL for example), and the rest is always required (lambda forms).

But probably doesn't make much of a difference performance-wise.

**Comment by tizoc** [comment]
@otabat I noticed that you also override `core.kl`, do you remember why?

**Comment by rkoeninger** [comment]
There's a flag in there to allow `define` to override sysfuncs:

https://github.com/otabat/shen-jvm/blob/c729d0debb0f1987898fe4da9c6054e302969741/shen/src/shen-replace/core-replace.shen#L43-L47

**Comment by rkoeninger** [comment]
> I still have to move all non-defun expressions inside a single (or many?) defun.

Does this mean there will be a `shen.init` function which the Shen implementation would call? That would prevent there being any top-level non-defuns, which would be nice.

```shen
(defun shen.init ()
  (do (set *installing-kl* true)
      (do ...
          (do (set *installing-kl* false)
              loaded)))
```

On occasion, I've wanted to make use of `*installing-kl*`, but I think it gets set to false at some point in `declarations` which might be in the middle of all the init expressions which is strange.

Or when you say "many" defuns, do you mean there might be a `shen.core.init`, `shen.sys.init`, etc? Would they have to be called in order?

**Comment by tizoc** [comment]
@rkoeninger yes, exactly that. Just pushed a new commit that includes this.

When I say "many defuns" I mean one for lambdas, and another for registering the type signatures. You need the lambdas on every program, you only need the signatures if you are going to typecheck code because you are compiling it.

**Comment by tizoc** [comment]
Note that after this transformation, there is a new `init.kl` file that ports have to load. That file provides the `shen.init` function that has to be called before anything else.

If a port can preprocess it and use an alternative method to initialize such code, then it can ignore the call to `shen.init`.

**Comment by rkoeninger** [comment]
The top-level forms are filtered out of the other `*.kl` files? So `toplevel.kl` will contain the `read-evaluate-print` function but not `(set *history* [])`. The `*history*` init will be in `init.kl`.

**Comment by tizoc** [comment]
That is correct. After the transformation what remains in all the `.kl` files is the license, followed by all the defuns. Everything that is not a defun is removed from that file and added to the body of the `shen.initialize` function that gets written to `init.kl`.

**Comment by tizoc** [comment]
When you get a chance please clone this branch, rebuild the klambda functions and test this in ShenScript, I'm very interested in seeing how it affects load times.

**Comment by rkoeninger** [comment]
Here's the results of trying this with ShenScript:

with the types-replace.kl from otabat:

```
generated js code size for kernel: 1098770 chars
test suite times: sync: 4s 482ms, async: 39s 408ms
async brave startup time: 65ms
async firefox startup time: 170ms
```

using this branch (at 5ba0e2a78fa4a492b0443a106369b983cb17246c)

```
generated js code size for kernel: 1184622 chars
test suite times: sync: 4s 180ms, async: 38s 332ms
async brave startup time: 50ms
async firefox startup time: 100ms
```

Overall performance is a about the same, but startup time is noticeably reduced even compared to the manual kernel optimization (both of the above were much improved over the standard 21.2 kernel).

**Comment by tizoc** [comment]
Great, thank you.

**Comment by rkoeninger** [comment]
Later I'll look at how this affects ShenSharp build and startup times.

This PR looks good to me. The next release after merge would have to be a major one, though (22.0), as it would break existing ports.

**Pull request merged**
