### PR TITLE
Echo option

### PR DESCRIPTION
**Pull request by rkoeninger**
This PR adds a flag named `*echo*` and a function `(echo X)` that takes `+`/`-` to change it to `true`/`false`.

When `*echo*` is `true`, the REPL and loading functions do not emit the results of evaluating expressions.

This would allow a file to start with `(echo -)`, then load whatever scripts and define whatever functions without filling out the command window/build log.

I just did this on a whim - is this of any use?

### CODE REVIEW

**Comment by tizoc** [comment]
Yes, it us useful. I can't revise and test it right now, but some comments:

- There are a bunch of unrelated commits here, can you clean up that? (this change can fit in a single clean commit without unrelated changes in it).
- I'm unsure about the `echo` name, I would use something less common (because once a name is taken by the kernel, no one can use it again for anything).
- I think that the changes could instead be part of a bigger feature (#4) that is the distinction between interactive (REPL) and non-interactive code execution (controlled by an `interactive-mode` flag or something like that).

**Comment by rkoeninger** [comment]
The newline changes in shendoc.html are the result of a git-windows quirk. I was obnoxious to have the file always in a changed state. I'll leave it alone next time.

`echo` was the only name that came to mind, as I was reminded of the Windows batch command `@echo off`.

I still don't completely understand #4, but this branch could get merged into whatever other PR when we know what we want to do with that.

**Comment by tizoc** [comment]
> The newline changes in shendoc.html are the result of a git-windows quirk.

Interesting. I think the reason is that shendoc.htm still has DOS-style newlines while the rest of the files are using UNIX-style newlines, let me update that on master so that it is not a problem anymore.

> I still don't completely understand #4, but this branch could get merged into whatever other PR when we know what we want to do with that.

#4 is in part, what you did here, but it also covers more ground. Shen as it is right now, has no concept of non-REPL execution, it just assumes that you will always load the REPL, and then start loading or writing code from there. But programs that are executed as scripts, or that are pre-compiled as stand-alone binaries have to behave differently, like for example not having to print reports that are meant for interactive mode (this is what you do in this PR), or having to handle errors and partial functions (when a function leaves out some pattern matching rules so that it doesn't cover every case, in the REPL you get a prompt to track the function when that happens) differently.

Anyway, there are many subtleties to it, and it is not just a matter of writing the code, the behaviors have to be well defined and documented, so it has to be done with some caution, thats why it has not been solved yet. If done well, what we get other than the desired behavior are new ways to optimize the final programs.

**Comment by tizoc** [comment]
@rkoeninger pushed the "endlines" branch, let me know if that solves your git issues and I will merge into master.

**Comment by rkoeninger** [comment]
@tizoc The `endlines` branch seems to address my issue, you can go ahead and merge that.

**Comment by rkoeninger** [comment]
This work can be done as a part of another enhancement as suggested. I'll leave this branch on my fork for reference.

**Pull request closed without merging**
