### PR TITLE
Shen 20 pre

### PR DESCRIPTION
**Pull request by tizoc**
# DO NOT MERGE

WIP of Shen 20 release.

### Whats in so far:

- Declared arity for:
  - `bound?`
  - `close`
  - `error-to-string`
  - `nl`
  - `limit`
  - `open`
  - `str`
  - `vector?`
- Fixed package prefix handling for internal package symbols.
- Added (and exposed) very basic dicts that are easily overridable with native hash tables by ports (for better performance, and interoperability with native hash tables).
- Reimplemented put/get on top of dicts.
- Reimplemented runtime function lookup using put/get.
- Added basic char-based io (it is the same as byte based io by default): `read-char-code` and `read-file-as-charlist`. Fixes issues on SBCL-Windows.
- Added `get/or`, `value/or`, `<-address/or` and `<-vector/or`. These work like their `/or`-less counterparts, but accept as an extra argument a continuation (`(freeze ...)`). Whenever their original versions would raise an exception, these variants will instead `thaw` the continuation and return it's result (unless the continuation raises an exception).
- Added `(fold-left F Acc List)`, `(fold-right F List Acc)` and `(for-each F List)`. `for-each` is like `map` but is explicit about not using the results, so it doesn't keep the results around.
- Added `(filter Predicate List)`. If `(Predicate Elt)` returns true, it will be kept in the list, otherwise it will be filtered out.
- Added `(exit ExitCode)`. Default implementation just ends the REPL loop and ignores `ExitCode`, ports have to provide their own `exit` function for that to work.
- Added `*sterror*` port for STDERR. By default it is an alias of `*stoutput*`.
- Changed `hash` so that 0 is a valid return value (wasn't valid before because of how property tables were implemented).
- Changed `make.shen` so that 19.2 can correctly compile the new version without needing two passes.
- Minor cleanup.

### Dict API

- `(dict Size)` — returns dictionary object.
- `(dict? Dict)` — predicate.
- `(dict-count Dict)` — returns dictionary items count.
- `(dict-> Dict Key Value)` — stores value.
- `(<-dict Dict Key)` — retrieves value if it exists or throws an error.
- `(<-dict/or Dict Key OrDefault)` — like `<-dict` but returns the result of thawing `OrDefault` instead of throwing an error when the key is missing.
- `(dict-rm Dict Key)` — removes value from a dictionary. 
- `(dict-fold F Dict Acc)` — walks the dictionary, calling `(F Key Value Acc)` for each item in it. The result of each call is the new value of `Acc`, once no more items are left, the final value of `Acc` is returned.
- `(dict-keys Dict)` — Returns  a list containing all keys in `Dict`.
- `(dict-values Dict)` — Returns a list containing all values in `Dict`.
- `(dict->alist Dict)` — Returns an assoc list builds from the pairs of key+value in `Dict`.

cc @rkoeninger @gravicappa @deech @mthom 

Trying to be minimalistic here in terms of scope, there are other things I would like to add (like command line handling, stderr ports, etc) but that would probably require more discussion and coordination between port implementors, so it is probably better to leave those for later.

Does anyone see any problem with the current dicts interface? (other than it is too minimal, more can be added later, either in the kernel or as a library, I'm only trying to cover what is required by the kernel itself for internal uses for now).

### CODE REVIEW

**Comment by tizoc** [comment]
Btw, `dicts` implemented in Shen have decent performance, so it is not a big deal for a port to not override them.

**Comment by tizoc** [comment]
To match `<-dict/or` and `get/or`, I think it would be a good idea to add default implementations for `value/or` and `<-address/or`. The advantage of doing so is that they can be used to replace the common pattern of `(trap-error (value|<-address ...) (/. E ...))`, allowing ports to override the `/or` versions with a faster alternative in cases where exception handling is expensive compared to the alternative (and for platforms where exception handling is cheap, nothing is lost anyway).

**Comment by gravicappa** [comment]
Those `*/or` functions looks nice.

**Comment by rkoeninger** [comment]
I gave this branch a try just now: built with 19.2 SBCL version, imported into and ran with latest ShenSharp. Test suite passed 100% and the KL import process and the test suite was noticeably faster (~20%). That's with no changes to my port.

So for `(dict Size)`, is that just the suggested initial capacity? Is it possible that one could always use `(dict 0)` and get the same results, but with likely slower initial performance?

**Comment by tizoc** [comment]
@rkoeninger thats great to hear. There is still some kernel code that has not been updated yet to take advantage of the new functions (I already made the updates, but not pushed yet). With that, and adding native overrides for the `/or` functions I think you would see some extra performance improvements.

Regarding `(dict Size)`, most ports would probably ignore the `Size` parameter when overriding dicts, but for some it can be useful. It is also required for the implementation of dicts in pure Shen (at least the simplistic one I did), because they are implemented on top of a fixed-size vector (no resizing will happen), and that `Size` param is what defines how big it will be.

`(dict 0)` will not work because the result would be a vector with no slots available, but `(dict 1)` will do (it will be slow, because with a single slot, what you get is a linear search over a list for the key you requested).

Something more elaborate could be implemented, but I don't think it is necessary, at least not until the current implementation turns out to be a problem. 

The main motivation for the dicts API is for ports to be able to override it with their own native implementations to share a common interface across ports, there is no use in making it more complicated knowing that it will never be able to compete with native implementations. Another motivation was making it easier for ports that cannot override `hash` (because they don't provide access to a native `hash` function, like Javascript) to still take advantage of their native hash tables to get Shen to perform better.

**Comment by tizoc** [comment]
After checking a bunch of hash table implementations in different languages, it seems to me asking for the count of items in the hash table is a widely implemented operation, so I added that to the dicts implemented in Shen.

**Comment by gravicappa** [comment]
Why not add more general `dict-fold` then? `dict-count` can be implemented as
```
(define dict-count Dict -> (dict-fold Dict (/. K V N (+ N 1)) 0))
```

**Comment by tizoc** [comment]
@gravicappa `dict-fold` is on its way, just have to be sure that it is not going to complicate things on any platform (imagine the situation where you can provide your native hash tables, but there is `dict-fold` that you have no way to override, the result is that you cannot override dicts at all because `dict-fold` would break). Anyway, so far I haven't found any such case, so it is seems safe to add.

`dict-count` will still stay the same though, because implementing it on top of `dict-fold` makes it too slow to be useful, and very different from what is usual in this cases (so far every platform that I have checked can give you the amount of elements in the hash table in constant time).

**Comment by tizoc** [comment]
@gravicappa `dict-fold` added https://github.com/Shen-Language/shen-sources/pull/30/commits/3d652cb5eae655f5e9e3bf07a309f4fdc81e73db#diff-45df0825b194a7af0bb30be6aabbf986R375

**Comment by tizoc** [comment]
Also `for-each`, `fold-left` and `fold-right` functions for lists.

**Comment by tizoc** [comment]
Something I still have to figure out is the types of dicts and its functions, but seems a bit complicated, maybe something better left for a future release.

**Comment by tizoc** [comment]
Ok, forget what I said about dict types, it was far easier than I tought (I expected to have to touch the t* algorithm a bit, but it was not necessary).

**Comment by tizoc** [comment]
The type of `dict->alist` is still missing, I'm not sure how it should look yet (or if I'm building the alist right, right now it is a list of `[Key | Value]`, but maybe it should be `[Key Value]`, not sure. Maybe I should just get rid of that function.

**Comment by gravicappa** [comment]
A minor thought about notation. I prefer to name conversion functions 'dict to alist' as `alist<-dict` or `alist-from-dict` because it makes code looks cleaner (to me):
```
(let Alist (alist<-dict Dict) ...)
```
instead of
```
(let Alist (dict->alist Dict) ...)
```
What do you think?

**Comment by tizoc** [comment]
I have no strong preference, but I agree with you, and slightly favor a `TO-of-FROM` format.

I used `FROM->TO` because of `n->string`, but it is the only function in the kernel that follows that format, there are no other functions that convert from one type to another (well, there is `str` but it is a bit different, it is more like Python's `repr`). But it feels a bit weird to me, specially when I look at `dict->` to the side of `dict->alist`. The `alist<-dict` gives me a similar feeling (because of `<-dict`), so I would rather have `X-of-Y` or `X-from-Y`.

Maybe it is a good idea to leave that function out for now and solve it in a future release (because of the mode complicated typing and not-so-obvious way the result should look (to me at least)), but this kind of functions will show up again soon, so already knowing how to name them is a plus.

**Comment by tizoc** [comment]
Btw, dicts get printed as `(dict ...)` for now:

```
(1-) (dict 100)
(dict ...)
```

Always the same, it doesn't matter the contents. I don't know what would be a good way to print them, or if we should add special constructors like `@v`, something like:

```
(@dict key value
       another-key another-value)
-->
(let D (dict 1000)
     _ (dict-> key value)
     _ (dict-> another-key another-value)
  D)
```

Something to think about for future releases.

**Comment by rkoeninger** [comment]
While we're piling on the functions, it would be nice to have a `filter` function for lists included, given that we already have `map` and now `fold` standard:

```
(define filter-h
    _ Acc [] -> (reverse Acc)
    F Acc [X | Xs] -> (filter-h F [X | Acc] Xs) where (F X)
    F Acc [_ | Xs] -> (filter-h F Acc Xs))

(define filter
    F Xs -> (filter-h F [] Xs))

(declare filter [[A --> boolean] --> [[list A] --> [list A]]])
```

Could also have `filter` for dicts?

**Comment by rkoeninger** [comment]
Also, the type declaration for `dict?` is [`[dict K V] --> boolean`](https://github.com/Shen-Language/shen-sources/pull/30/commits/7a59f237cc29fd7bf6d82083cd1aa83ec88afa63#diff-e03710ed3bc8dec0c89fb72105cea3f8R108) where for most types, it looks like this: `(declare number? [A --> boolean])`. Is that an intentional difference?

**Comment by tizoc** [comment]
@rkoeninger not intentional, that was a mistake, thanks for spotting it.

**Comment by tizoc** [comment]
@rkoeninger `filter` added.

**Comment by tizoc** [comment]
Other dict functions (some suggested by @rkoeninger in one of the opened issues) that may be added now or in a future release:

- `(dict-has? Dict Key)` (not sure about the name) that returns true/false depending on if `Key` has a binding in `Dict`. Default implementation would be built on top of `<-dict/or`.
- `(dict-clear Dict)`, removes all bindings from `Dict`. Not sure how widespread this operation is, but I would guess it is common enough to not be an issue. The default implementation can be built on top of `dict-keys` + `dict-rm`.
- `(dict-copy Dict)`, returns a new dict instance, with all bindings copied from `Dict`. Default implementation can be built on top of `dict-fold`.
- `(dict-walk F Dict)`, like `dict-fold` but results are ignored.

And if dicts backing storage ever handles resizing:

- `(dict-reset Dict)`, like `dict-clear`, but also resets the underlying storage to its initial size. Platforms that don't control the size of the underlying storage can make this an alias of `dict-clear`.

**Comment by tizoc** [comment]
Added documentation for the system functions (taken from the entry I created on the wiki for the older ones, and added docs for the ones added in this release).

https://github.com/tizoc/shen-sources/blob/shen-20-pre/doc/system-functions.md

If anyone spots any errors (typos, missing stuff, stuff that don't exist anymore, or anything that is just plain wrong) please let me know. Also if anyone can provide a better organization (or feel like adding more docs), you are welcome.

**Comment by tizoc** [comment]
Added default implementations for `*sterror*` (defaults to an alias of `*stoutput*`) and `(exit ExitCode)` function. The default implementation of `exit` ignores the exit code, but ends the REPL loop.

**Comment by tizoc** [comment]
@rkoeninger when you compile a newer version of Shen using an older one, the older one doesn't know that all those symbols are systemf, so when compiling from shen to kl, it is going to prefix them with "shen.", something you don't want. All those systemf calls in make.shen are there to expand the list of systemf symbols known to the version compiling the new one. Earlier ones don't have to be added.

**Comment by rkoeninger** [comment]
@tizoc So symbols older than Shen 17 (17 is the recommended minimum in the readme) don't have to be added, but the list will grow indefinitely until the minimum version is increased? Has anything changed that would require the minimum version to be increased above 17?

**Comment by tizoc** [comment]
@rkoeninger well, right now, the real minor version is 19.3, because before that there was a bug in how packages were being handled (I don't remember the range of versions but I know 19.2 has that bug). Remember the `shen.shen` -> `shen` thing? (then back to `shen.shen`), thats the bug I'm talking about.

I think the most realistic option is to just have each major version be compilable with the one preceding it. Having to test all other versions would be cumbersome, and I don't think it adds much value.

My plan is to create a new repo containing the `.kl` files already generated so that no one has to compile from `.shen` to `.kl` after a new version has been released, so it is not going to be an issue anyway.

**Comment by rkoeninger** [comment]
@tizoc "just have each major version be compilable with the one preceding it" - Agreed.

"new repo containing the .kl files already generated" - I've been meaning to bring this up. It would also be helpful for automated builds to be able to pull down a `.zip` or `.tar.gz` file containing `klambda/` and `tests/`. For my port, they're checked into my repo, which is not ideal.

These downloads could be available from this repo, associated with the release tags we already make. A separate repo seems like overkill.

**Comment by tizoc** [comment]
My goal was to just have a clean diff between releases, which useful for port maintainers (that was the main purpose of this repository before it became the new official home of the OS kernel, I just created a new release here each time Mark released a new versions). Afaik Github doesn't let you customize the release tarballs anymore, so a separate repo is what I came up as a solution.

I don't know if other port maintainers care about the clean diffs, it was useful to me before to understand what Mark did between releases (the changelog was too skim), but it is not something I need anymore now when I'm introducing changes myself (or been involved in reviewing changes introduced by others).

**Comment by rkoeninger** [comment]
@tizoc Go to releases > Draft a new release > "Attach binaries by dropping them here or selecting them".

I [just added a custom release `.zip` to a repo of mine](https://github.com/rkoeninger/ShenSharp/releases/tag/v0.8.1.0).

**Comment by tizoc** [comment]
Thank you! I was pretty sure this had been removed a while ago, but obviously I was wrong (maybe I confused it with something else).

**Comment by tizoc** [comment]
Just modified my local copy for it to be able to run Shen 20.

Without any changes (other than overriding an optimization that is not needed anymore and that prevented Shen 20 from running) the test suite run time went down from 5.7 seconds to 4.6 seconds, which is good news.

**Pull request merged**
